name: Cleanup PR Preview

on:
  pull_request:
    types: [closed]
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  cleanup-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Remove preview directory
        run: |
          if [ -d "preview" ]; then
            rm -rf preview
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "Remove preview for closed PR #${{ github.event.number }}" || exit 0
            git push origin gh-pages
          else
            echo "Preview directory not found, nothing to clean up"
          fi
      
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const { repo, owner } = context.repo;
            const pr_number = context.issue.number;
            
            github.rest.issues.createComment({
              owner,
              repo,
              issue_number: pr_number,
              body: `🧹 **Preview cleaned up!**\n\nThe preview deployment has been removed since this PR was closed.`
            });