name: Cleanup PR Preview

on:
  pull_request:
    types: [closed]
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  cleanup-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const { repo, owner } = context.repo;
            const pr_number = context.issue.number;
            
            // Delete previous preview comments
            const comments = await github.rest.issues.listComments({
              owner,
              repo,
              issue_number: pr_number,
            });
            
            for (const comment of comments.data) {
              if (comment.user.login === 'github-actions[bot]' && 
                  (comment.body.includes('🚀 **Preview deployed!**') || 
                   comment.body.includes('🧹 **Preview cleaned up!**'))) {
                await github.rest.issues.deleteComment({
                  owner,
                  repo,
                  comment_id: comment.id,
                });
              }
            }
            
            // Create cleanup comment
            github.rest.issues.createComment({
              owner,
              repo,
              issue_number: pr_number,
              body: `🧹 **Preview cleaned up!**\n\nThe preview deployment will be automatically removed by Firebase Hosting in 30 days, or you can manually delete the preview channel from the Firebase Console if needed.`
            });