name: Deploy PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: "preview-${{ github.event.number }}"
  cancel-in-progress: true

jobs:
  build-and-deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Optimize images
        run: node scripts/optimize-images.js
      
      - name: Build PR preview
        run: npm run build:preview
        env:
          NEXT_PUBLIC_BASE_PATH: ""
      
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './out'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions - PR #${{ github.event.number }}"
          alias: pr-${{ github.event.number }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const { repo, owner } = context.repo;
            const pr_number = context.issue.number;
            const previewUrl = `https://pr-${pr_number}--${{ secrets.NETLIFY_SITE_NAME }}.netlify.app`;
            
            // Delete previous comments from this action
            const comments = await github.rest.issues.listComments({
              owner,
              repo,
              issue_number: pr_number,
            });
            
            for (const comment of comments.data) {
              if (comment.user.login === 'github-actions[bot]' && comment.body.includes('🚀 **Preview deployed!**')) {
                await github.rest.issues.deleteComment({
                  owner,
                  repo,
                  comment_id: comment.id,
                });
              }
            }
            
            // Create new comment
            github.rest.issues.createComment({
              owner,
              repo,
              issue_number: pr_number,
              body: `🚀 **Preview deployed!**\n\nYou can preview your changes at: ${previewUrl}\n\n*This preview will be updated automatically when you push new commits to this PR.*\n\n**Note:** Preview is now hosted on Netlify using GitHub Actions deployment method.`
            });